// /Script/Icarus.IcarusWeatherActionData
// size 0x6B0, declared in Icarus/Source/Icarus/IcarusGenerated/WeatherActions/WeatherActionsRowHandle.h

USTRUCT()
struct FIcarusWeatherActionData : public FIcarusTableRowBase
{
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftClassPtr<UIcarusWeatherAction> WeatherActionComponent;  // 0x0018, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bIsRampingUp;  // 0x0040, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UTexture2D> TimelineIcon;  // 0x0048, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FSlateColor TimelineTailBrush;  // 0x0070, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float ExposureMultiplier;  // 0x0098, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TMap<float, FModifier> ExposureModifiers;  // 0x00A0, size 0x50
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Rain;  // 0x00F0, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_RainStart;  // 0x00F4, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_RainEnd;  // 0x00F8, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Rain;  // 0x0100, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableFillable_Rain;  // 0x0128, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Rainfall_Millilitre_Start;  // 0x012C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Rainfall_Millilitre_End;  // 0x0130, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Clouds;  // 0x0134, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_CloudsStart;  // 0x0138, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_CloudsEnd;  // 0x013C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Clouds;  // 0x0140, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bGeneratesLightning;  // 0x0168, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float MinLightningInterval;  // 0x016C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float MaxLightningInterval;  // 0x0170, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bGeneratesThunder;  // 0x0174, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float ThunderIntensity;  // 0x0178, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Debris;  // 0x017C, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_DebrisStart;  // 0x0180, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_DebrisEnd;  // 0x0184, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Debris;  // 0x0188, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableAction_Temperature;  // 0x01B0, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Temperature_Start;  // 0x01B4, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Temperature_End;  // 0x01B8, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) int32 Perception_Percentage;  // 0x01BC, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Wind;  // 0x01C0, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableAction_Wind;  // 0x01C1, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_WindStart;  // 0x01C4, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_WindEnd;  // 0x01C8, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Wind;  // 0x01D0, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float StormTier;  // 0x01F8, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float StormWindDamagePeriod;  // 0x01FC, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float UnzipChance;  // 0x0200, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float UnzipbuildingCountMultiplier;  // 0x0204, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float UnzipbuildingDamageMultiplier;  // 0x0208, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableEndAllWindDamageTrigger;  // 0x020C, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_EndAllWindDamageTrigger;  // 0x0210, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bWindTopplesTrees;  // 0x0238, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float TreeToppleMinInterval;  // 0x023C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float TreeToppleMaxInterval;  // 0x0240, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float TreeToppleStrengthThreshold;  // 0x0244, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableDamage_Deployables;  // 0x0248, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Damage_Deployables_MinInterval;  // 0x024C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Damage_Deployables_MaxInterval;  // 0x0250, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Damage_Deployables_Intensity;  // 0x0254, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableDamage_Players;  // 0x0258, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Damage_Players_MinInterval;  // 0x025C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Damage_Players_MaxInterval;  // 0x0260, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Damage_Players_Intensity;  // 0x0264, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableFireExtinguish;  // 0x0268, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float FireExtinguish_RollChanceMulti;  // 0x026C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float FireExtinguish_MinInterval;  // 0x0270, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float FireExtinguish_MaxInterval;  // 0x0274, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Sand;  // 0x0278, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_SandStart;  // 0x027C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_SandEnd;  // 0x0280, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Sand;  // 0x0288, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Sand_Buildup;  // 0x02B0, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_Sand_BuildupStart;  // 0x02B4, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_Sand_BuildupEnd;  // 0x02B8, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Snow;  // 0x02BC, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_SnowStart;  // 0x02C0, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_SnowEnd;  // 0x02C4, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Snow;  // 0x02C8, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Snow_Buildup;  // 0x02F0, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_Snow_BuildupStart;  // 0x02F4, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_Snow_BuildupEnd;  // 0x02F8, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Snow_Storm;  // 0x02FC, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_Snow_StormStart;  // 0x0300, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_Snow_StormEnd;  // 0x0304, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Ash;  // 0x0308, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_AshStart;  // 0x030C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_AshEnd;  // 0x0310, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Ash;  // 0x0318, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Ash_Buildup;  // 0x0340, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_Ash_BuildupStart;  // 0x0344, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_Ash_BuildupEnd;  // 0x0348, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Embers;  // 0x034C, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_EmbersStart;  // 0x0350, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_EmbersEnd;  // 0x0354, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Embers;  // 0x0358, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Smoke;  // 0x0380, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_SmokeStart;  // 0x0384, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_SmokeEnd;  // 0x0388, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Smoke;  // 0x0390, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_AcidRain;  // 0x03B8, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_AcidRainStart;  // 0x03BC, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_AcidRainEnd;  // 0x03C0, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_AcidRain;  // 0x03C8, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Hail;  // 0x03F0, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_HailStart;  // 0x03F4, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_HailEnd;  // 0x03F8, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_HailRain;  // 0x0400, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Radiation;  // 0x0428, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_RadiationStart;  // 0x042C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_RadiationEnd;  // 0x0430, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Radiation;  // 0x0438, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_FogColor;  // 0x0460, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_FogColorStart;  // 0x0464, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_FogColorEnd;  // 0x0468, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FLinearColor FogColorLinear;  // 0x046C, size 0x10
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_FogDensity;  // 0x047C, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_FogDensityStart;  // 0x0480, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_FogDensityEnd;  // 0x0484, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_FogDensity;  // 0x0488, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_FogExtinction;  // 0x04B0, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_FogExtinctionStart;  // 0x04B4, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_FogExtinctionEnd;  // 0x04B8, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_FogExtinction;  // 0x04C0, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Whiteout;  // 0x04E8, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_WhiteoutStart;  // 0x04EC, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_WhiteoutEnd;  // 0x04F0, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Whiteout;  // 0x04F8, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_LightningCloud;  // 0x0520, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_LightningCloudStart;  // 0x0524, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_LightningCloudEnd;  // 0x0528, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_LightningCloud;  // 0x0530, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_RadiationWind;  // 0x0558, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_RadiationWindStart;  // 0x055C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_RadiationWindEnd;  // 0x0560, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_RadiationWind;  // 0x0568, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableVisuals_Speckles;  // 0x0590, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_SpecklesStart;  // 0x0594, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Severity_SpecklesEnd;  // 0x0598, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_Speckles;  // 0x05A0, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableDamageTag;  // 0x05C8, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_DamageTag;  // 0x05D0, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float DamageTag_Intensity;  // 0x05F8, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float DamageTag_DutyCycle;  // 0x05FC, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FTagQueriesRowHandle DamageTag_Query;  // 0x0600, size 0x18
    UPROPERTY(EditAnywhere, BlueprintReadWrite) EIcarusDamageType DamageTag_DamageType;  // 0x0618, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnableProcessorClog;  // 0x0619, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_ProcessorClog;  // 0x0620, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bEnablePlayerItemDamageTag;  // 0x0648, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) bool bDamageFocusedItem;  // 0x0649, size 0x1
    UPROPERTY(EditAnywhere, BlueprintReadWrite) TSoftObjectPtr<UCurveFloat> Curve_PlayerItemDamageTag;  // 0x0650, size 0x28
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float PlayerItemDamageTag_Intensity;  // 0x0678, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float PlayerItemDamageTag_DutyCycle;  // 0x067C, size 0x4
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FTagQueriesRowHandle PlayerItemDamageTag_Query;  // 0x0680, size 0x18
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FInventoryIDEnum InventoryID;  // 0x0698, size 0x10
    UPROPERTY(EditAnywhere, BlueprintReadWrite) EIcarusDamageType PlayerItemDamageTag_DamageType;  // 0x06A8, size 0x1
};
