// /Script/Engine.EdGraphSchema
// Derives from: UObject
// size 0x28, declared in Engine/Source/Runtime/Engine/Classes/EdGraph/EdGraphSchema.h

UCLASS(Abstract)
class UEdGraphSchema : public UObject
{

    // Virtual functions that start here:
    //   ArePinsCompatible, BackwardCompatibilityNodeConversion, BreakNodeLinks, BreakPinLinks
    //   BreakSinglePinLink, CanCreateConnection, CanCreateNewNodes, CanDuplicateGraph, CanEncapuslateNode
    //   CanMergeNodes, CanVariableBeDropped, ClearPinWatch, ConstructBasicPinTooltip, CopyPinLinks
    //   CreateAutomaticConversionNodeAndConnections, CreateConnectionDrawingPolicy
    //   CreateDefaultNodesForGraph, CreateSubstituteNode, DoesDefaultValueMatch
    //   DoesDefaultValueMatchAutogenerated, DoesSupportPinWatching, DropPinOnNode, DroppedAssetsOnGraph
    //   DroppedAssetsOnNode, DroppedAssetsOnPin, DuplicateGraph, FadeNodeWhenDraggingOffPin
    //   ForceVisualizationCacheClear, GetAssetsGraphHoverMessage, GetAssetsNodeHoverMessage
    //   GetAssetsPinHoverMessage, GetContextMenuActions, GetCreateCommentAction
    //   GetCurrentVisualizationCacheID, GetGraphContextActions, GetGraphDisplayInformation, GetGraphType
    //   GetNodeSelectionCount, GetParentContextMenuName, GetPinTypeColor, HandleGraphBeingDeleted
    //   IsCacheVisualizationOutOfDate, IsDelegateCategory, IsPinBeingWatched, IsPinDefaultValid, IsSelfPin
    //   IsTitleBarPin, MarkBlueprintDirtyFromNewNode, MovePinLinks, OnPinConnectionDoubleCicked
    //   RecombinePin, ReconstructNode, RequestVariableDropOnNode, RequestVariableDropOnPanel
    //   RequestVariableDropOnPin, ResetPinToAutogeneratedDefaultValue, SafeDeleteNodeFromGraph
    //   ShouldAlwaysPurgeOnModification, ShouldHidePinDefaultValue, ShouldShowAssetPickerForPin, SplitPin
    //   SupportsDropPinOnNode, TryCreateConnection, TrySetDefaultObject, TrySetDefaultText
    //   TrySetDefaultValue
};
