// /Script/Engine.EdGraphPin_Deprecated
// Derives from: UObject
// size 0x118, declared in Engine/Source/Runtime/Engine/Classes/EdGraph/EdGraphPin.h

UCLASS(MinimalAPI)
class UEdGraphPin_Deprecated : public UObject
{
public:
    UPROPERTY() FString PinName;  // 0x0028, size 0x10
    UPROPERTY() FString PinToolTip;  // 0x0038, size 0x10
    UPROPERTY() TEnumAsByte<EEdGraphPinDirection> Direction;  // 0x0048, size 0x1
    UPROPERTY() FEdGraphPinType PinType;  // 0x0050, size 0x58
    UPROPERTY() FString DefaultValue;  // 0x00A8, size 0x10
    UPROPERTY() FString AutogeneratedDefaultValue;  // 0x00B8, size 0x10
    UPROPERTY() UObject* DefaultObject;  // 0x00C8, size 0x8
    UPROPERTY() FText DefaultTextValue;  // 0x00D0, size 0x18
    UPROPERTY() TArray<UEdGraphPin_Deprecated*> LinkedTo;  // 0x00E8, size 0x10
    UPROPERTY() TArray<UEdGraphPin_Deprecated*> SubPins;  // 0x00F8, size 0x10
    UPROPERTY() UEdGraphPin_Deprecated* ParentPin;  // 0x0108, size 0x8
    UPROPERTY() UEdGraphPin_Deprecated* ReferencePassThroughConnection;  // 0x0110, size 0x8
};
