DELEGATE() void OnAbandonProspectEventSignature(const FResAbandonProspect& Response);  // parameters 0x1
DELEGATE() void OnBackToHabEventSignature(const FResBackToHab& Response);  // parameters 0x1
DELEGATE() void OnCanJoinProspectEventSignature(const FResCanJoinProspect& Response);  // parameters 0x1
DELEGATE() void OnChatMessage(const FIcarusChatMessage& ChatMessage);  // parameters 0x30
DELEGATE() void OnCheckProspectExpiredEventSignature(const FResCheckProspectExpired& Response);  // parameters 0x2
DELEGATE() void OnClaimNotificationAttachmentsEventSignature(const FResClaimNotificationAttachments& Response);  // parameters 0x48
DELEGATE() void OnClaimProspectEventSignature(const FResClaimProspect& Response);  // parameters 0xA8
DELEGATE() void OnConnectMessage(bool bSuccess);  // parameters 0x1
DELEGATE() void OnCreateCharacterEventSignature(const FResCreateCharacter& Response);  // parameters 0xD8
DELEGATE() void OnCreateDropshipEventSignature(const FResCreateDropship& Response);  // parameters 0x100
DELEGATE() void OnDeleteCharacterEventSignature(const FResDeleteCharacter& Response);  // parameters 0x1
DELEGATE() void OnDeleteDropshipEventSignature(const FResDeleteDropship& Response);  // parameters 0x20
DELEGATE() void OnDeleteNotificationEventSignature(const FResDeleteNotification& Response);  // parameters 0x18
DELEGATE() void OnExchangeCurrencyEventSignature(const FResExchangeCurrency& Response);  // parameters 0x18
DELEGATE() void OnGenerateProspectsEventSignature(const FResGenerateProspects& Response);  // parameters 0x18
DELEGATE() void OnGetAllProspectsEventSignature(const FResGetAllProspects& Response);  // parameters 0x18
DELEGATE() void OnGetAvailableProspectsEventSignature(const FResGetAvailableProspects& Response);  // parameters 0x18
DELEGATE() void OnGetChallengesEventSignature(const FResGetChallenges& Response);  // parameters 0x18
DELEGATE() void OnGetCharacterLoadoutEventSignature(const FResGetCharacterLoadout& Response);  // parameters 0x140
DELEGATE() void OnGetCharacterProfileEventSignature(const FResGetCharacterProfile& Response);  // parameters 0xD8
DELEGATE() void OnGetCharactersEventSignature(const FResGetCharacters& Response);  // parameters 0x18
DELEGATE() void OnGetCreditsEventSignature(const FResGetCredits& Response);  // parameters 0x8
DELEGATE() void OnGetDropshipsEventSignature(const FResGetDropships& Response);  // parameters 0x18
DELEGATE() void OnGetLastProspectEventSignature(const FResGetLastProspect& Response);  // parameters 0xB0
DELEGATE() void OnGetLoadoutInventoryEventSignature(const FResLoadoutInventory& Response);  // parameters 0x18
DELEGATE() void OnGetMetaInventoryEventSignature(const FResGetMetaInventory& Response);  // parameters 0x20
DELEGATE() void OnGetMetaResourceEventSignature(const FResGetMetaResources& Response);  // parameters 0x18
DELEGATE() void OnGetNotificationsEventSignature(const FResGetNotifications& Response);  // parameters 0x18
DELEGATE() void OnGetPreparedLoadoutEventSignature(const FResPreparedLoadout& Response);  // parameters 0x50
DELEGATE() void OnGetProspectEventSignature(const FResGetProspect& Response);  // parameters 0xE8
DELEGATE() void OnGetProspectReportEventSignature(const FResGetProspectReport& Response);  // parameters 0xD0
DELEGATE() void OnGetProspectSummaryEventSignature(const FResGetProspectSummary& Response);  // parameters 0x118
DELEGATE() void OnGetUserProfileEventSignature(const FResGetUserProfile& Response);  // parameters 0x50
DELEGATE() void OnHostCandidateEventSignature(const FResHostCandidate& Response);  // parameters 0x38
DELEGATE() void OnJoinProspectEventSignature(const FResJoinProspect& Response);  // parameters 0xA8
DELEGATE() void OnLobbyMessageEventSignature(const FResLobbyMessage& Response);  // parameters 0x18
DELEGATE() void OnLoginFailMessage(ELoginFailure ErrorCode);  // parameters 0x1
DELEGATE() void OnMatchUpdateMessage(bool bSuccess, const FMatchUpdate& MatchUpdate);  // parameters 0x88
DELEGATE() void OnModifyDropshipEventSignature(const FResModifyDropship& Response);  // parameters 0x100
DELEGATE() void OnMoveMetaInventoryItemEventSignature(const FResMoveMetaInventoryItem& Response);  // parameters 0x18
DELEGATE() void OnPackageLoadoutEventSignature(const FResPackageLoadout& Response);  // parameters 0x108
DELEGATE() void OnProspectExpiredEventSignature(const FResProspectExpired& Response);  // parameters 0x1
DELEGATE() void OnReadNotificationEventSignature(const FResReadNotification& Response);  // parameters 0x18
DELEGATE() void OnRemoveEnvirosuitEventSignature(const FResRemoveEnvirosuit& Response);  // parameters 0x60
DELEGATE() void OnRemoveMetaItemEventSignature(const FResRemoveMetaInventoryItem& Response);  // parameters 0x20
DELEGATE() void OnRemoveSelectedDropshipEventSignature(const FResRemoveSelectedDropship& Response);  // parameters 0x8
DELEGATE() void OnRepairWorkshopItemEventSignature(const FResRepairWorkshopItem& Response);  // parameters 0x30
DELEGATE() void OnReplicateWorkshopItemEventSignature(const FResReplicateWorkshopItem& Response);  // parameters 0x30
DELEGATE() void OnResetCharacterEventSignature(const FResResetCharacter& Response);  // parameters 0xD8
DELEGATE() void OnResetCharacterProspectStateEventSignature(const FResResetCharacterProspectState& Response);  // parameters 0x1
DELEGATE() void OnResumeProspectEventSignature(const FResResumeProspect& Response);  // parameters 0xF8
DELEGATE() void OnSelectDropshipEventSignature(const FResSelectDropship& Response);  // parameters 0x8
DELEGATE() void OnSelectEnvirosuitEventSignature(const FResSelectEnvirosuit& Response);  // parameters 0x60
DELEGATE() void OnSetResourceSplitEventSignature(const FResSetResourceSplit& Response);  // parameters 0x1
DELEGATE() void OnSettleProspectEventSignature(const FResSettleProspect& Response);  // parameters 0xA8
DELEGATE() void OnSyncAccountFlagsEventSignature(const FResSyncAccountFlags& Response);  // parameters 0x18
DELEGATE() void OnSyncAccountTalentsEventSignature(const FResSyncAccountTalents& Response);  // parameters 0x18
DELEGATE() void OnSyncCharacterTalentsEventSignature(const FResSyncCharacterTalents& Response);  // parameters 0x18
DELEGATE() void OnTalentRefundEventSignature(const FResTalentRefund& Response);  // parameters 0x30
DELEGATE() void OnUnlockAccountFlagsEventSignature(const FResUnlockAccountFlags& Response);  // parameters 0x18
DELEGATE() void OnUnlockCharacterFlagsEventSignature(const FResUnlockCharacterFlags& Response);  // parameters 0x18
DELEGATE() void OnUnlockWorkshopItemEventSignature(const FResUnlockWorkshopItem& Response);  // parameters 0x28
DELEGATE() void OnUnpackageLoadoutEventSignature(const FResUnpackageLoadout& Response);  // parameters 0x2
DELEGATE() void OnUpdateChallengeProgressEventSignature(const FResUpdateChallengeProgress& Response);  // parameters 0x1
DELEGATE() void OnUpdateCharacterLoadoutEventSignature(const FResUpdateCharacterLoadout& Response);  // parameters 0x18
DELEGATE() void OnUpdateCharacterProgressEventSignature(const FResUpdateCharacterProgress& Response);  // parameters 0x1
DELEGATE() void OnUpdateCharacterProspectLocationEventSignature(const FResUpdateCharacterProspectLocation& Response);  // parameters 0x1
DELEGATE() void OnUpdateConnectionStringMessage(const FConnectionString& ConnectionString);  // parameters 0x38
DELEGATE() void OnUpdateCosmeticsEventSignature(const FResUpdateCosmetics& Response);  // parameters 0xD8
DELEGATE() void OnUpdateFactionMissionProgressEventSignature(const FResUpdateFactionMissionProgress& Response);  // parameters 0x1
DELEGATE() void OnUpdateProspectEventSignature(const FResUpdateProspect& Response);  // parameters 0x2
DELEGATE() void OnUpdateTrackedStatsEventSignature(const FResUpdateTrackedStats& Response);  // parameters 0x1
